export const GRID_ACTIONS = {
  STATUS_INITIAL: "STATUS_INITIAL",
  STATUS_SELECTED: "STATUS_SELECTED",
  STATUS_COMPLETED: "STATUS_COMPLETED",
  ADD_TO_VISIBLE: "ADD_TO_VISIBLE",
  CLEAR_VISIBLE: "CLEAR_VISIBLE",
  RESTART: "RESTART",
};
